package student.gpa;

import Settings.IOrganizer;
import static Settings.ButtonSettings.BoxSelectedItem;
import static Settings.ButtonSettings.ResetAllButton;
import Settings.textsettings;
import java.text.DecimalFormat;


public class StudentGPAcalculate extends javax.swing.JFrame implements IOrganizer{


    public StudentGPAcalculate() {
        initComponents();
        getEdits();
        textsettings.setOnlyNumber(mathcreditField);
        textsettings.setOnlyNumber(chemistrycreditField);
        textsettings.setOnlyNumber(englishcreditField);
        textsettings.setOnlyNumber(biologycreditField);
        textsettings.setOnlyNumber(historycreditField);
        textsettings.setOnlyNumber(physicscreditField);
        
        
    }

    @Override
    public void getEdits(){
        enterPanel.setLayout(null);
        enterPanel.setVisible(true);
        studentPanel.setLayout(null);
        studentPanel.setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mathcreditField = new javax.swing.JTextField();
        historycreditField = new javax.swing.JTextField();
        chemistrycreditField = new javax.swing.JTextField();
        biologycreditField = new javax.swing.JTextField();
        englishcreditField = new javax.swing.JTextField();
        physicscreditField = new javax.swing.JTextField();
        mathReset = new javax.swing.JButton();
        hisReset = new javax.swing.JButton();
        cheReset = new javax.swing.JButton();
        bioReset = new javax.swing.JButton();
        engReset = new javax.swing.JButton();
        phyReset = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        mathBox = new javax.swing.JComboBox<>();
        hisBox = new javax.swing.JComboBox<>();
        chemBox = new javax.swing.JComboBox<>();
        bioBox = new javax.swing.JComboBox<>();
        engBox = new javax.swing.JComboBox<>();
        phyBox = new javax.swing.JComboBox<>();
        studentPanel = new javax.swing.JPanel();
        chegrade = new javax.swing.JTextField();
        biograde = new javax.swing.JTextField();
        enggrade = new javax.swing.JTextField();
        phygrade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mathgrade = new javax.swing.JTextField();
        hisgrade = new javax.swing.JTextField();
        historycreditField1 = new javax.swing.JTextField();
        physicscreditField1 = new javax.swing.JTextField();
        englishcreditField1 = new javax.swing.JTextField();
        biologycreditField1 = new javax.swing.JTextField();
        chemistrycreditField1 = new javax.swing.JTextField();
        mathcreditField1 = new javax.swing.JTextField();
        gpaLabel = new javax.swing.JLabel();
        gpaField = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student GPA System");
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));

        enterPanel.setBackground(new java.awt.Color(255, 255, 204));
        enterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 51), new java.awt.Color(255, 255, 0)), "Enter information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 20))); // NOI18N
        enterPanel.setForeground(new java.awt.Color(255, 255, 204));
        enterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mathematics");
        enterPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 121, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("History");
        enterPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 176, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chemistry");
        enterPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 237, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Biology");
        enterPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 298, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("English");
        enterPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 358, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Physics");
        enterPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 415, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Subjects");
        enterPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 66, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Credit");
        enterPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 66, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Grade");
        enterPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 66, -1, -1));

        mathcreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(mathcreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 118, 116, -1));

        historycreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(historycreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 173, 116, -1));

        chemistrycreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(chemistrycreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 234, 116, -1));

        biologycreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(biologycreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 295, 116, -1));

        englishcreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(englishcreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 355, 116, -1));

        physicscreditField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterPanel.add(physicscreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 412, 116, -1));

        mathReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mathReset.setText("Reset");
        mathReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mathReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathResetActionPerformed(evt);
            }
        });
        enterPanel.add(mathReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 117, -1, -1));

        hisReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hisReset.setText("Reset");
        hisReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hisReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hisResetActionPerformed(evt);
            }
        });
        enterPanel.add(hisReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 172, -1, -1));

        cheReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cheReset.setText("Reset");
        cheReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cheReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheResetActionPerformed(evt);
            }
        });
        enterPanel.add(cheReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 233, -1, -1));

        bioReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bioReset.setText("Reset");
        bioReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bioReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioResetActionPerformed(evt);
            }
        });
        enterPanel.add(bioReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 294, -1, -1));

        engReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        engReset.setText("Reset");
        engReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        engReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engResetActionPerformed(evt);
            }
        });
        enterPanel.add(engReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 354, -1, -1));

        phyReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phyReset.setText("Reset");
        phyReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        phyReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phyResetActionPerformed(evt);
            }
        });
        enterPanel.add(phyReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 411, -1, -1));

        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setText("Add");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        enterPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 504, 97, 39));

        Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        enterPanel.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 504, 97, 39));

        mathBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mathBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        mathBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(mathBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 118, 60, -1));

        hisBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        hisBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(hisBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 173, 60, -1));

        chemBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        chemBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(chemBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 234, 60, -1));

        bioBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        bioBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(bioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 295, 60, -1));

        engBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        engBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        engBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(engBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 355, 60, -1));

        phyBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F" }));
        phyBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPanel.add(phyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 412, 60, -1));

        studentPanel.setBackground(new java.awt.Color(204, 255, 204));
        studentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)), "Student GPA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 20))); // NOI18N
        studentPanel.setForeground(new java.awt.Color(204, 255, 204));
        studentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chegrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(chegrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 219, 116, -1));

        biograde.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(biograde, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 263, 116, -1));

        enggrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(enggrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 308, 116, -1));

        phygrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(phygrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 355, 116, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Subjects");
        studentPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 81, 100, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Credit");
        studentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 81, 65, 28));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Grade");
        studentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 81, 59, 28));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Mathematics");
        studentPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 127, 101, 28));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("History");
        studentPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 173, 100, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Chemistry");
        studentPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 219, 101, 28));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Biology");
        studentPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 263, 100, 28));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("English");
        studentPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 311, 101, 28));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Physics");
        studentPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 355, 100, 28));

        mathgrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(mathgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 127, 116, -1));

        hisgrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(hisgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 171, 116, -1));

        historycreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(historycreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 171, 116, -1));

        physicscreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(physicscreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 355, 116, -1));

        englishcreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(englishcreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 308, 116, -1));

        biologycreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(biologycreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 263, 116, -1));

        chemistrycreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(chemistrycreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 219, 116, -1));

        mathcreditField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(mathcreditField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 127, 116, -1));

        gpaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gpaLabel.setText("GPA :");
        studentPanel.add(gpaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 502, -1, -1));

        gpaField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPanel.add(gpaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 499, 180, -1));

        CalculateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });
        studentPanel.add(CalculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 432, -1, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(enterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mathResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathResetActionPerformed
        ResetAllButton(mathBox,mathcreditField);
    }//GEN-LAST:event_mathResetActionPerformed

    private void hisResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hisResetActionPerformed
        ResetAllButton(hisBox,historycreditField);
    }//GEN-LAST:event_hisResetActionPerformed

    private void cheResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheResetActionPerformed
        ResetAllButton(chemBox,chemistrycreditField);
    }//GEN-LAST:event_cheResetActionPerformed

    private void bioResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioResetActionPerformed
        ResetAllButton(bioBox,biologycreditField);
    }//GEN-LAST:event_bioResetActionPerformed

    private void engResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engResetActionPerformed
        ResetAllButton(engBox,englishcreditField);
    }//GEN-LAST:event_engResetActionPerformed

    private void phyResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phyResetActionPerformed
        ResetAllButton(phyBox,physicscreditField);
    }//GEN-LAST:event_phyResetActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        physicscreditField1.setText(physicscreditField.getText());
        englishcreditField1.setText(englishcreditField.getText());
        biologycreditField1.setText(biologycreditField.getText());
        chemistrycreditField1.setText(chemistrycreditField.getText());
        historycreditField1.setText(historycreditField.getText());
        mathcreditField1.setText(mathcreditField.getText());
        
        BoxSelectedItem(phyBox,phygrade);
        BoxSelectedItem(engBox,enggrade);
        BoxSelectedItem(bioBox,biograde);
        BoxSelectedItem(mathBox,mathgrade);
        BoxSelectedItem(hisBox,hisgrade);
        BoxSelectedItem(chemBox,chegrade);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        ResetAllButton(phyBox,physicscreditField);
        ResetAllButton(engBox,englishcreditField);
        ResetAllButton(bioBox,biologycreditField);
        ResetAllButton(chemBox,chemistrycreditField);
        ResetAllButton(hisBox,historycreditField);
        ResetAllButton(mathBox,mathcreditField);
    }//GEN-LAST:event_ResetActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        double totalpoints,totalcredits,gpa;
        double m_point,h_point,b_point,p_point,e_point,c_point;
        double m_credit,h_credit,b_credit,p_credit,e_credit,c_credit;
        m_point=Double.valueOf(mathcreditField.getText())*Double.valueOf(mathcreditField1.getText());
        h_point=Double.valueOf(historycreditField.getText())*Double.valueOf(historycreditField1.getText());
        b_point=Double.valueOf(biologycreditField.getText())*Double.valueOf(biologycreditField1.getText());
        p_point=Double.valueOf(physicscreditField.getText())*Double.valueOf(physicscreditField1.getText());        
        e_point=Double.valueOf(englishcreditField.getText())*Double.valueOf(englishcreditField1.getText());           
        c_point=Double.valueOf(chemistrycreditField.getText())*Double.valueOf(chemistrycreditField1.getText());            
        
        m_credit=Double.valueOf(mathcreditField.getText());
        h_credit=Double.valueOf(historycreditField.getText());
        b_credit=Double.valueOf(biologycreditField.getText());
        p_credit=Double.valueOf(physicscreditField.getText());  
        e_credit=Double.valueOf(englishcreditField.getText());        
        c_credit=Double.valueOf(chemistrycreditField.getText());        
                
        totalpoints=m_point+h_point+b_point+p_point+e_point+c_point;
        totalcredits=m_credit+h_credit+b_credit+p_credit+e_credit+c_credit;
        
        DecimalFormat df = new DecimalFormat("0.00");
        gpa=totalpoints/totalcredits;
        gpaField.setText(String.valueOf(df.format(gpa)));
    }//GEN-LAST:event_CalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGPAcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGPAcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGPAcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGPAcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGPAcalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton Reset;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> bioBox;
    private javax.swing.JButton bioReset;
    private javax.swing.JTextField biograde;
    private javax.swing.JTextField biologycreditField;
    private javax.swing.JTextField biologycreditField1;
    private javax.swing.JButton cheReset;
    private javax.swing.JTextField chegrade;
    private javax.swing.JComboBox<String> chemBox;
    private javax.swing.JTextField chemistrycreditField;
    private javax.swing.JTextField chemistrycreditField1;
    private javax.swing.JComboBox<String> engBox;
    private javax.swing.JButton engReset;
    private javax.swing.JTextField enggrade;
    private javax.swing.JTextField englishcreditField;
    private javax.swing.JTextField englishcreditField1;
    private javax.swing.JPanel enterPanel;
    private javax.swing.JTextField gpaField;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JComboBox<String> hisBox;
    private javax.swing.JButton hisReset;
    private javax.swing.JTextField hisgrade;
    private javax.swing.JTextField historycreditField;
    private javax.swing.JTextField historycreditField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> mathBox;
    private javax.swing.JButton mathReset;
    private javax.swing.JTextField mathcreditField;
    private javax.swing.JTextField mathcreditField1;
    private javax.swing.JTextField mathgrade;
    private javax.swing.JComboBox<String> phyBox;
    private javax.swing.JButton phyReset;
    private javax.swing.JTextField phygrade;
    private javax.swing.JTextField physicscreditField;
    private javax.swing.JTextField physicscreditField1;
    private javax.swing.JPanel studentPanel;
    // End of variables declaration//GEN-END:variables
}
